version: '3'
services:

  server:
    build: ./server
    depends_on:
      - "mongodb"
    ports:
      - "8181:8181"
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "4200:4200" 
    networks:
      - app-network 

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './database/data:/data/db'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

